### ISSUE TITLE
Config file API key

### ISSUE THREAD

**Issue by sk9la** [Nemoden/gogpt#3]
Hi,

Love your chatgpt script.

The only suggestion I have is to delete the API key file `~/.gogpt`, instead add an entry `api_key` in the config file `~/.config/gogpt/config.yaml` just like that:
```
api_key: XXXXXXXXXXXXXXXXXXXX
renderer: plain
model: text-davinci-003
max_tokens: 2048
temperature: 0.5
```

**Comment by Nemoden** [comment]
@sk9la hi! Thanks 🙏 

the only reason the API key is separate from config is because it’s a secret. It’s quite common that people store their entire ~/.config in git and host on github as part of their “dotfiles”

I was afraid someone could leak their API key this way.

Initially api key indeed was part of the config file. My reasoning was that it’s convenient to have everything in one place. But for the security concerns I decided to separate the API key in its own file.

What I will do is add a CLI flag to view/edit config + list all the files created by chatgpt. May also consider leaving a comment inside ~/.gogpt hinting a user where this file is coming from.

At this moment I’ll mark it as “won’t do” because of the reasons above
